using System;
using System.Linq;
using FirebirdSql.EntityFrameworkCore.Firebird.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Logging;
using NUnit.Framework;

namespace FirebirdSql.EntityFrameworkCore.Firebird.Tests
{
	[TestFixture]
	public class BasicTests
	{
		[Test]
		public void SimpleSelect()
		{
			using (var db = GetDbContext())
			{
				var data = db.Set<MonAttachment>().ToList();
				Assert.IsNotEmpty(data);
			}
		}

		[Test]
		public void SelectWithWhere()
		{
			using (var db = GetDbContext())
			{
				var data = db.Set<MonAttachment>()
					.Where(x => x.AttachmentName.Trim() != string.Empty && x.Timestamp.Second > -1)
					.ToList();
				Assert.IsNotEmpty(data);
			}
		}

		[Test]
		public void SimpleInsert()
		{
			using (var db = GetDbContext())
			{
				db.Database.ExecuteSqlCommand("recreate table test (id int generated by default as identity primary key, name varchar(20))");
				var entity = new TestEntity() { Id = -1, Name = "foobar" };
				db.Set<TestEntity>().Add(entity);
				db.SaveChanges();
				Assert.AreNotEqual(-1, entity.Id);
			}
		}

		static TestDbContext GetDbContext()
		{
			var result = new TestDbContext();
			var loggerFactory = result.GetService<ILoggerFactory>();
			loggerFactory.AddConsole();
			return result;
		}
	}

	class TestDbContext : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseFirebird(@"database=localhost:test.fdb;user=sysdba;password=masterkey");
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			var monAttachmentConf = modelBuilder.Entity<MonAttachment>();
			monAttachmentConf.HasKey(x => x.AttachmentId);
			monAttachmentConf.Property(x => x.AttachmentId).HasColumnName("MON$ATTACHMENT_ID");
			monAttachmentConf.Property(x => x.AttachmentName).HasColumnName("MON$ATTACHMENT_NAME");
			monAttachmentConf.Property(x => x.Timestamp).HasColumnName("MON$TIMESTAMP");
			monAttachmentConf.ToTable("MON$ATTACHMENTS");

			var testEntityConf = modelBuilder.Entity<TestEntity>();
			testEntityConf.Property(x => x.Id).HasColumnName("ID")
				.UseFirebirdIdentityColumn();
			testEntityConf.Property(x => x.Name).HasColumnName("NAME");
			testEntityConf.ToTable("TEST");
		}
	}

	class MonAttachment
	{
		public int AttachmentId { get; set; }
		public string AttachmentName { get; set; }
		public DateTime Timestamp { get; set; }
	}

	class TestEntity
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}
}
