SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE '127.0.0.1:C:\ROLE_PROVIDER2.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UNICODE_FSS;

CREATE TABLE ROLES (
    ROLENAME         VARCHAR(255) NOT NULL,
    APPLICATIONNAME  VARCHAR(255) NOT NULL
);


CREATE TABLE USERSINROLES (
    USERNAME         VARCHAR(255) NOT NULL,
    ROLENAME         VARCHAR(255) NOT NULL,
    APPLICATIONNAME  VARCHAR(255) NOT NULL
);
